### ISSUE TITLE
Format Clarification

### ISSUE THREAD

**Issue by PhoneDroid** [temper-studios/graph-file-format#1]
Could you please clarify what mixed nested data resolves to.

## My Undestanding

*Conversions from .graph to .yaml*

<br>

```graph
a { 1.0 }
b { "Hello World" }
```

```yaml
a : 1.0
b : 'Hello World'
```

<br>

```graph
a { 1 2 3 }
```

```yaml
a:
- 1
- 2
- 3
```

<br>

```graph
a { b { 1 } }
```

```yaml
a:
  b : 1
```

<br>
<br>

## Unsure

*The README example*

```graph
node { 1 2 3.0 "hello" child { -1.0 } }
```

as a node in the array?

```yaml
node:
- 1
- 2
- 3.0
- 'hello'
-
   child : 1
```

( also in this case, would multiple properties be one big node or all separate nodes with only one property ( b ) each ? )

or separated?

```yaml
node:
  values:
  - 1
  - 2
  - 3.0
  - 'hello'
  properties:
    child : 1
```

**Comment by PhoneDroid** [comment]
Or are mixed nested child nodes just named but are actually unnamed objects?

```graph
1 2 child { 3 } other { c { 4 } d { 5 } }
```

```yaml
- 1
- 2
- 
  - 3
-
  c : 4
  d : 5
```
